### ISSUE TITLE
关于matlab中数据处理的内容

### ISSUE THREAD

**Issue by luzeng365** [FesianXu/PLSTM#1]
您好，非常高兴能够在GitHub上找到您复现了Part-aware LSTM的方法的代码，但在数据处理方面您事先将.skeleton的文件转换成.mat格式，希望您在方便的时候能上传matlab部分代码，或者能发一份到我邮箱：luzeng@njust.edu.cn。十分感谢您的分享

**Comment by FesianXu** [comment]
@luzeng365
Hi, i process the raw .skeleton file in python script writen by myself instead of the matlab script for the low efficiency of the MATLAB:) I would update the process script soon! Thanks for your attention.

**Comment by FesianXu** [comment]
@luzeng365
Hi, thanks for your attention. I'm sorry to tell you i have lost my script but you could refer the official script [link](https://github.com/shahroudy/NTURGB-D/tree/master/Matlab). I just use the 3d coordinate data (x,y,z) and save them in .mat files. You could delete the other information like quaternion.

**Comment by FesianXu** [comment]
BTW, in detail, you could format your own data formation like (nframes, 25, 3) or (nframes, 75) and so on.

**Comment by luzeng365** [comment]
I am very glad to receive your reply.but could you offer some data with .mat, i think it could be  will help me when i deal with the data, the path of those data may "raw_path = '/home/fesian/AI_workspace/datasets/HRI40/raw/mats/'", thank you!

**Comment by FesianXu** [comment]
@luzeng365
I have updated and push an example .mat file in `datas` folder. I hope it would help you. Feel free to contact me if you still confuse about the data formation or any other question:)

**Comment by wangxiaohangxdu** [comment]
I have some problem  with the raw skeleton file,  how can i contact u

**Comment by wangxiaohangxdu** [comment]
@FesianXu

**Comment by FesianXu** [comment]
please just put your problems here. @wangxiaohangxdu

**Comment by wangxiaohangxdu** [comment]
I am a student at Sichuan University. I saw you at the University of Electronic Science and Technology. I am just engaged in the topic of behavior recognition. I want to know what the original data set represents, and how to process the data into h5 format. The problem is a bit complicated, there are a lot of problems, I hope you can answer it patiently.

**Comment by wangxiaohangxdu** [comment]
@FesianXu

**Comment by wangxiaohangxdu** [comment]
Maybe  you can contact me by 917261060@qq.com @FesianXu

**Comment by FesianXu** [comment]
@i didn't process the raw data(txt formation) into h5 because i use pytorch and tensorflow. So i just parse the raw txt files into a numpy arrays(`.npy` files) or `.mat` arrays(using in the matlab or python).  as for how to parse the original txt data, you can refer the NTU RGBD repository: https://github.com/shahroudy/NTURGB-D/tree/master/Matlab
(although it is in matlab, it is easy to implement in python)

**Comment by wangxiaohangxdu** [comment]
I am very grateful for your answer, I will try the conversion file again. Thank you again! @FesianXu
