### ISSUE TITLE
Doubt regarding the joint values in divide_config

### ISSUE THREAD

**Issue by Anirudh257** [FesianXu/PLSTM#4]
Firstly, thanks a lot for implementing the Part-LSTM code and sharing it. I had a doubt in the file:  
PartAwareLSTMCell.py 
   divide config:
    head:  [ 3, 4,              1,2,21]
    r_arm: [ 5, 6, 7, 8,22,23,  1,2,21]
    l_arm: [ 9,10,11,12,24,25,  1,2,21]
    r_leg: [13,14,15,16,        1,2,21]
    l_leg: [17,18,19,20,        1,2,21]

In 
![image](https://user-images.githubusercontent.com/16001446/58612910-ccf69a80-82d1-11e9-98a9-acf9c18b0977.png)

Why are the joints: **1, 2 and 21** repeating so many times for all the parts? For head, I can understand why it is present. But how come for the remaining 4, it is present?

**Comment by FesianXu** [comment]
Hi Anirudh
I'm glad that this repository is helpful to you.
I repeat the joint **1,2 and 21** because i believe that the movement of arms and legs will also affect the backbone. Since the original paper didn't give any segment protocol, I just group the legs and arms with the backbone. But I'm not sure if it's the best solution, maybe you can try to remove the repeated joints and compare the performance.

**Comment by Anirudh257** [comment]
Thanks for replying promptly. I will repeat the results with and without the joints and try again.
